### ISSUE TITLE
Option to remove failed command?

### ISSUE THREAD

**Issue by tmpm697** [AlexanderThaller/histdb-rs#10]

**Comment by AlexanderThaller** [comment]
I guess something like this?

```
--filter-failed
  Filter out commands that did not finish with a return code of 0 (success).
```

**Comment by tmpm697** [comment]
Yeah, I actually use 3rd to filter out failed commands already.

I don't know about `Rust` but I'll give it serious try.

**Comment by AlexanderThaller** [comment]
Im gonna give it a try if thats ok with you :D

**Comment by tmpm697** [comment]
Totally ok, thanks, haha.

**Comment by AlexanderThaller** [comment]
@tmpm697 https://github.com/AlexanderThaller/histdb-rs/pull/11 if you want to check it out :D

**Comment by tmpm697** [comment]
noice, that'll remove my `awk` command to filter out failed comands, potential speed up a bit. Oh, i love it.

I did quick glance at source code, it quickly become vage :), but I got some ideas of each file/mod.
