### ISSUE TITLE
ERROR histdb_rs > can not write to stdout: Broken pipe (os error 32)

### ISSUE THREAD

**Issue by tmpm697** [AlexanderThaller/histdb-rs#19]
I got this error `ERROR histdb_rs > can not write to stdout: Broken pipe (os error 32)` when try to run:
```
histdb-rs --disable-formatting --entries-count 10000000 --filter-failed | head
OR:
histdb-rs --disable-formatting --entries-count 10000000 | head
```
version: histdb-rs 2.0.0
os: archlinux up-to-date

expect somehow don't get this error.

**Comment by AlexanderThaller** [comment]
That seems to be a general rust problem from what I can see

https://github.com/rust-lang/rust/issues/35108

Will investigate.
