### ISSUE TITLE
Do not save "<space>command"

### ISSUE THREAD

**Issue by tmpm697** [AlexanderThaller/histdb-rs#9]
Traditional history will avoid to save " ls" that command has a space before it, user don't want to save that command.

I notice histdb-rs still save those commands, need to exclude them.

**Comment by tmpm697** [comment]
`histdb-rs` will just print command without space before the command, so it's not aware of this kind of command, but in `csv` it appears to save correctly.

**Comment by AlexanderThaller** [comment]
Yeah sounds like a nice idea. I usually use these sub-commands if I don't want some commands tho show up in the history:

```
    disable
            Disable history recording for current session

    enable
            Enable history recording for current session
```

But prefixing them with a space could be nice as well and more ergonomic.

Probably some configuration would be nice to change that behavior but there is no configuration at the moment.

Do you want to implement it? For now we can just have the default behavior to filter out commands beginning with a space.  Other wise I can also try to implement it.

**Comment by tmpm697** [comment]
Add space before unwanted command seems to avail or default in most of popular shell (bash/zsh) and it'd be good if we keep it that way.

I don't know about `Rust`, I hesitated to learn it from 2014 but now I think it's a chance to revert it. I'll take this but don't expect it will be implemented soon :P

**Comment by AlexanderThaller** [comment]
Sure no worries :D. If you have questions feel free to ask I'm always glad if I can help. Rust needs a bit of time investment before things feel productive but it becomes a great language and I personally like it more and more :D.
